language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/
    - /home/travis/virtualenv/python2.7
install:
  - pip install flake8 --download-cache $HOME/.pip-cache
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
before_script:
  - flake8 .
script:
  - py.test
