sudo: required
dist: xenial
python:
  - "2.7"
cache:
  apt: true
  # TODO local node modules path correct?
  directories:
    - $HOME/data

before_install:
    - apt-get update -yy
    - apt-get install make
install:
    - make stack-up

before_script:
  - bower install -F

script:
   - make test
   - make doc

# after_success:
#   make coveralls
