sudo: required
dist: trusty
language: python
python:
  - "2.7"
cache:
  apt: true
  directories:
    - $HOME/data
    # Permission denied
    # - /var/lib/docker

before_install:
    - type docker
    - docker --version
    - type docker-compose
    - docker-compose --version

    - sudo apt-get update -yy
    - sudo apt-get install -yy make

    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker pull bbiskup/purkinje_dev:latest || true

install:
    - make stack-up

# before_script:

script:
   - make test
   - make doc

   - make build-docker-dist-img

after_success:
    - true

deploy:
    #   make coveralls

    # push latest version of dev image to speed up future builds
    - docker tag purkinje_dev bbiskup/purkinje_dev:latest
    - docker tag purkinje_dev bbiskup/purkinje_dev:$TRAVIS_BUILD_NUMBER
    - docker push bbiskup/purkinje_dev:latest
    - docker push bbiskup/purkinje_dev:$TRAVIS_BUILD_NUMBER

    # push distribution image
    - docker tag code_dist bbiskup/purkinje_dist:latest
    - docker tag code_dist bbiskup/purkinje_dist:$TRAVIS_BUILD_NUMBER
    - docker push bbiskup/purkinje_dist:latest
    - docker push bbiskup/purkinje_dist:$TRAVIS_BUILD_NUMBER
