sudo: required
dist: trusty
python:
  - "2.7"
cache:
  apt: true
  directories:
    - $HOME/data
    # Permission denied
    # - /var/lib/docker

before_install:
    - type docker
    - docker --version
    - type docker-compose
    - docker-compose --version

    # - sudo service docker stop
    # - wget https://get.docker.com/builds/Linux/x86_64/docker-1.11.0.tgz
    # - mkdir dockertmp
    # - tar xzvf docker-1.11.0.tgz -C dockertmp
    # - chmod +x dockertmp/docker/*
    # - sudo mv dockertmp/docker/* /usr/bin
    # - sudo service docker restart
    # - docker ps
    # - sudo bash -c "curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
    # - sudo chmod +x /usr/local/bin/docker-compose
    # - type docker-compose
    # - docker-compose --version

    - sudo apt-get update -yy
    - sudo apt-get install -yy make

install:
    - make stack-up

before_script:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker pull bbiskup/purkinje_dev:latest || true

script:
   - make test
   - make doc

after_success:
    #   make coveralls
    - docker tag -f purkinje_dev bbiskup/purkinje_dev:latest
    - docker tag purkinje_dev bbiskup/purkinje_dev:$TRAVIS_BUILD_NUMBER
    - docker push bbiskup/purkinje_dev:latest
    - docker push bbiskup/purkinje_dev:$TRAVIS_BUILD_NUMBER
