sudo: required
dist: xenial
python:
  - "2.7"
cache:
  apt: true
  # TODO local node modules path correct?
  directories:
    - $HOME/data

before_install:
    - sudo apt-get update -yy
    - sudo apt-get install make
    - sudo (curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose)
    - sudo chmod +x /usr/local/bin/docker-compose
install:
    - make stack-up

script:
   - make test
   - make doc

# after_success:
#   make coveralls
