language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/
    - /usr/lib/node_modules/
    - /home/travis/virtualenv/python2.7
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  # Python
  - pip install flake8 --download-cache $HOME/.pip-cache
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
  - pip install -r dev-requirements.txt --download-cache $HOME/.pip-cache

  # JS
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get -y update
  - sudo apt-get -y install nodejs
  - sudo npm install -g --dev

before_script:
  - flake8 .
  - bower install -F

script:
  - py.test