version: "2"
services:
    base:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - default
    purkinje:
        extends: base
        ports:
            - "5000:5000"
    dev:
        extends: base
        restart: "no"
        privileged: yes
        volumes:
            - ./purkinje:/code/purkinje
            - ./purkinje/static/bower_components:/code/purkinje/static/bower_components
            - ./docs:/code/docs
            - ./docker/purkinje.yml:/code/purkinje.yml
            - ./tests:/code/tests
            - ./testdata:/code/testdata
            - ./meta/python/pytest.ini:/code/pytest.ini
            - ./meta/js/.jshintrc:/code/.jshintrc
            - ./meta/js/karma.conf.js:/code/karma.conf.js
            - ./meta/js/mocha.conf.js:/code/mocha.conf.js
            - ./meta/js/protractor-conf.js:/code/protractor-conf.js
            - ./data/webassets_cache:/code/purkinje/static/.webassets_cache
            - ./Dockerfile.dist:/code/Dockerfile.dist

            # Access to Docker daemon on host
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "5001:5000"
        links:
            - purkinje
        entrypoint:
            - bash
            - -c
        command: bash
