version: "2"
services:
    base:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - default
    purkinje:
        extends: base
        ports:
            - "5000:5000"
    dev:
        extends: base
        restart: "no"
        privileged: yes
        volumes:
            - ./purkinje:/code/purkinje
            - ./docs:/code/docs
            - ./docker/purkinje.yml:/code/purkinje.yml
            - ./tests:/code/tests
            - ./testdata:/code/testdata
            - ./pytest.ini:/code/pytest.ini
            - ./tox.ini:/code/tox.ini
            - ./.jshintrc:/code/.jshintrc
            - ./karma.conf.js:/code/karma.conf.js
            - ./mocha.conf.js:/code/mocha.conf.js
            - ./protractor-conf.js:/code/protractor-conf.js
            - ./data/tox:/code/.tox
            # - /tmp/.X11-unix:/tmp/.X11-unix
        ports:
            - "5001:5000"
        links:
            - purkinje
        environment:
            - DISPLAY=unix${DISPLAY}
        entrypoint:
            - bash
            - -c
        command: bash
