version: "2"
services:
    base:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - default
    purkinje:
        extends: base
        ports:
            - "5000:5000"
    dev:
        extends: base
        restart: "no"
        volumes:
            - ./purkinje:/code/purkinje
            - ./docker/purkinje.yml:/code/purkinje.yml
            - ./tests:/code/tests
            - ./testdata:/code/testdata
            - ./pytest.ini:/code/pytest.ini
            - ./tox.ini:/code/tox.ini
            - ./.jshintrc:/code/.jshintrc
            - ./data/tox:/code/.tox
        ports:
            - "5001:5000"
        entrypoint:
            - bash
            - -c
        command: bash
