version: "2"
services:
    base:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - default
    purkinje:
        extends: base
        ports:
            - "5000:5000"
    dev:
        extends: base
        restart: "no"
        privileged: yes
        volumes:
            - ./purkinje:/code/purkinje
            - ./purkinje/static/bower_components:/code/purkinje/static/bower_components
            - ./docs:/code/docs
            - ./docker/purkinje.docker.yml:/code/purkinje.yml
            - ./tests:/code/tests
            - ./testdata:/code/testdata
            - ./pytest.ini:/code/pytest.ini
            - .jshintrc:/code/.jshintrc
            - ./karma.conf.js:/code/karma.conf.js
            - ./mocha.conf.js:/code/mocha.conf.js
            - ./protractor-conf.js:/code/protractor-conf.js
            - ./data/webassets_cache:/code/purkinje/static/.webassets_cache
            - ./data/tox:/code/.tox
            # - ./data/dist:/code/dist
            - ./Dockerfile.dist:/code/Dockerfile.dist
            - ./docker-compose.dist.yml:/code/docker-compose.dist.yml

            # Access to Docker daemon on host
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock

            # For Chrome
            # - /dev/shm:/dev/shm

            # To debug Chrome using host X11
            # - /tmp/.X11-unix:/tmp/.X11-unix
        ports:
            - "5001:5000"
        links:
            - purkinje
        entrypoint:
            - bash
            - -c
        command: bash
